
server:
  port: 9003


spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: iprp-dev
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
      url: jdbc:p6spy:mysql://127.0.0.1:3306/no_catch_test?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: 123456

ink:
  swagger-enable: true
  #ms
  token-expire-mills: 86400000
  attach-config:
    server: http://localhost:9003/
    server-path: /Users/zhangrui/upload
  person-import-template: "personImportTemplate.xlsx"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


