server:
  port: 9002
  tomcat:
    #请求体大小 -1不限制 默认值2MB
    max-swallow-size: -1
  # undertow的配置
  # 可在 pom.xml spring-boot-starter-web中切换 tomcat
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      worker: 256
      io: 16

  servlet:
    context-path: /ink-api

spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: iprp-dev
  datasource:
    druid:
      stat-view-servlet:
        enabled: false
        reset-enable: false
        login-password: B1ockch@in
        login-username: hyperchain
        allow:
      web-stat-filter:
        enabled: true
      #      type: com.alibaba.druid.pool.DruidDataSource
      #      driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/no_catch?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: 123456
  redis:
    database: 1
    host: 127.0.0.1
    port: 9379
    password: tr@cidence@redis

ink:
  swagger-enable: true
  #ms
  token-expire-mills: 86400000
  attach-config:
    server: http://localhost:9003/
    server-path: /Users/zhangrui/upload
  person-import-template: "personImportTemplate.xlsx"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    show-extensions: true
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: cn.hyperchain.ink.web
#  default-flat-param-object: false

knife4j:
  enable: true
  setting:
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    language: zh_cn

  openapi:
    title: Ink项目接口文档
    description: "接口文档"
    email: ink@hyperchain.cn
    concat:
    url: https://www.filoink.cn
    version: v1.0
    license: inkweb 1.0
    license-url: https://www.hyperchain.cn
    terms-of-service-url: https://www.hyperchain.cn
    group:
      bacckendWeb:
        group-name: WEB_V1.0.1
        api-rule: package
        path-rule: ANT
        api-rule-resources:
          - cn.hyperchain.ink.web
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: WEB_V1.0.1
#      group: default


logging:
  config: classpath:logback-spring.xml
  level:
    root: info